export const DASBOARD_REQUESTED = 'DASBOARD_REQUESTED';
export const DASBOARD_REQUEST_SUCCESS = 'DASBOARD_REQUEST_SUCCESS';
export const DASBOARD_REQUEST_FAIL = 'DASBOARD_REQUEST_FAIL';
export const DASBOARD_UPDATE_INPUT = 'DASBOARD_UPDATE_INPUT';