# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoPush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # Pods for demoPush

  target 'demoPushTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demoPush-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demoPush-tvOS

  target 'demoPush-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
