# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushNotifications' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotifications
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  target 'PushNotifications-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushNotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PushNotifications-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotifications-tvOS

end
