# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstReactProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'Firebase/Core'
   	pod 'Firebase/Messaging'

  # Pods for FirstReactProject

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'FirstReactProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FirstReactProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirstReactProject-tvOS

  target 'FirstReactProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
